name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
            echo "hello world"
            echo "run multiple shell commands by adding the pipe symbol"
      - name: Print goodbye
        run: echo "Done - bye!"
